[reflect] 3/n Do not forget to substitute containers when inheriting a callable
In scope of: OSIP-51, KT-75463

Notes on the tests in the diff:

1. readWriteProperty & definitelyNonNullSAM. I am sure that KT-47030 is
   still relevant. Why the tests have started passing - I have no clue
   and I do not think that it's important
2. genericWithBoundsOnKJK & substitutionOverrideOnComplexHierarchy:
   these tests were already failing with flexibility mismatch.

   Technically, this commit makes the situation even worse for these
   tests, cause now the diff between K1 and new reflect is even bigger.
   I've debugged these tests, the duplicated members didn't show up out
   of pure not-substituted-containers-coincidence. Now, the tests are
   more fair. The duplicated members should get fixed once the
   flexibility mismatch is fixed in these tests.

Besides the mentioned tests, this commit fixes three reflection tests
which are not in the diff:

1. Fix FirLightTreeBlackBoxCodegenTestGenerated.Reflection.Properties#testKotlinPropertyInheritedInJava.
   Before this commit, it was failing as:

    Expected :OK
    Actual   :Fail: property references from :: and from properties differ: var J.prop: kotlin.String != var J.prop: kotlin.String
    <Click to see difference>

    org.opentest4j.AssertionFailedError: expected: <OK> but was: <Fail: property references from :: and from properties differ: var J.prop: kotlin.String != var J.prop: kotlin.String>
            at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
            at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
            at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
            at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:188)
            at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1167)
            at org.jetbrains.kotlin.test.services.JUnit5Assertions.assertEquals(JUnit5Assertions.kt:73)
            at org.jetbrains.kotlin.test.Assertions.assertEquals$default(Assertions.kt:40)
            at org.jetbrains.kotlin.test.backend.handlers.JvmBoxRunner.callBoxMethodAndCheckResult(JvmBoxRunner.kt:155)
            at org.jetbrains.kotlin.test.backend.handlers.JvmBoxRunner.callBoxMethodAndCheckResultWithCleanup(JvmBoxRunner.kt:92)
            ...

2. Fix FirLightTreeBlackBoxCodegenTestGenerated.Reflection.MethodsFromAny#testFakeOverrideEqualsHashCode.
   Before this commit, it was failing as:

    Illegal value: <fun B<U>.foo(U): kotlin.Unit>.
    java.lang.AssertionError: Illegal value: <fun B<U>.foo(U): kotlin.Unit>.
            at kotlin.test.DefaultAsserter.fail(DefaultAsserter.kt:16)
            at kotlin.test.Asserter.assertTrue(Assertions.kt:766)
            at kotlin.test.DefaultAsserter.assertTrue(DefaultAsserter.kt:11)
            at kotlin.test.Asserter.assertNotEquals(Assertions.kt:794)
            at kotlin.test.DefaultAsserter.assertNotEquals(DefaultAsserter.kt:11)
            at kotlin.test.AssertionsKt__AssertionsKt.assertNotEquals(Assertions.kt:80)
            at kotlin.test.AssertionsKt.assertNotEquals(Unknown Source)
            at kotlin.test.AssertionsKt__AssertionsKt.assertNotEquals$default(Assertions.kt:79)
            at kotlin.test.AssertionsKt.assertNotEquals$default(Unknown Source)
            at FakeOverrideEqualsHashCodeKt.box(fakeOverrideEqualsHashCode.kt:20)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.jetbrains.kotlin.test.backend.handlers.JvmBoxRunner.runBoxInCurrentProcess(JvmBoxRunner.kt:170)
            ...

3. org.jetbrains.kotlin.test.runners.codegen.NewReflectionFakeOverridesImplementationTestGenerated.TypeParameters#testFakeOverrides