[Tests] Fix binary compatibility with the stable JPS plugin tests
Currently, the JPS tests are run in the IntelliJ IDEA project, and tests
are carried over in a JAR (so tests are running straight from the JAR).

Moreover, classpath for running Kotlin JPS tests in IntelliJ IDEA is
mixed. The JPS plugin test JAR, 'kotlinc.kotlin-jps-plugin-tests',
comes from the stable version of Kotlin, while all other Kotlin compiler
classes are from the newer artifact (literally 'master' in the
Cooperative 'kt-master' setup). Such an inconcistency may lead to
unintentional ABI breakages that only become apparent during 'kt-master'
merges.

After my previous refactoring of 'MockLibraryUtil', the 'compileKotlin'
function became an instance one. That made the JPS tests to fail with
the following error:

---
java.lang.IncompatibleClassChangeError: Expected static method 'void
org.jetbrains.kotlin.test.AbstractMockLibraryUtil.compileKotlin
(java.lang.String, java.io.File, java.util.List, java.lang.String[])'
---

The change re-introduces a deprecated static method on 'MockLibraryUtil'
so the older artifacts can call it.

For a long-term solution, see KT-84534 or KT-84535.